language: python

install:
  - pip install virtualenv==13.1.2  # for Python 3.2
  - pip install tox>=1.8
  - pip install .
script:
  - tox

matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35-dj18
      - TOXENV=py35-dj19
    - python: 3.4
      env:
      - TOXENV=py34-dj17
      - TOXENV=py34-dj18
      - TOXENV=py34-dj19
    - python: 3.3
      env:
      - TOXENV=py33-dj15
      - TOXENV=py33-dj16
      - TOXENV=py33-dj17
      - TOXENV=py33-dj18
    - python: 3.2
      env:
      - TOXENV=py32-dj15
      - TOXENV=py32-dj16
      - TOXENV=py32-dj17
      - TOXENV=py32-dj18
    - python: 2.7
      env:
      - TOXENV=py27-dj14
      - TOXENV=py27-dj15
      - TOXENV=py27-dj16
      - TOXENV=py27-dj17
      - TOXENV=py27-dj18
      - TOXENV=py27-dj19
    - python: 2.6
      env:
      - TOXENV=py26-dj14
      - TOXENV=py26-dj15
      - TOXENV=py26-dj16
